# Generated by Django 3.1a1 on 2020-05-21 15:23

import cased_django.cased_model_event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("test_app", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
            ],
            bases=(models.Model, cased_django.cased_model_event.CasedModelEvent),
        )
    ]
